---
apiVersion: v1
kind: Secret
metadata:
  name: deployment-repo-auth-apple
  namespace: apple
stringData:
  identity: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAYEAv4SPlDQJKbnLAlke8Pyo/e1ltaBoczQyMzRhGa9bexJBwGGyu8gA
    69immPaWYYjZeyBP2cZ32CtMBJd4+9O4pwizHgDQZqRwfje+6UrtU/XgvCQVcQKrGxsiYa
    Fdsf6u/bXt1gluOZTAQOhksVkESq+9/24H2ZSXoeo/YeDZNiLPeDnQr0UV4nECNhdLSial
    4CAaDIBemlUM2/iSy6YrU74EE7ukVF235m9ZOSavZcMFpUYX/GM4Eb9Wfl92vAAgsXjUrO
    9Brn2O7Ph4pb1/EfUONuxIpk6hY1CiPyjqQN9/fi4v6nl50lgu7GfPuRHor72ahFiCMID7
    IV55fIyF+0i77pgDs7NKHOPBWCk9hkwRP9wcLeK7CI9GMBlzMJIRsoC3xmziqjvzcFrMMz
    8lrD3Bf3RmqER3jvqSHimmVJYRQc0PiSzgmyn2kkauogvJvF55JKjvxBcOpqZOCzcRbtot
    sntcbebXvvsTpCr4rS+X0fBtpN4fK2nneU1KjcO1AAAFkB9XHL0fVxy9AAAAB3NzaC1yc2
    EAAAGBAL+Ej5Q0CSm5ywJZHvD8qP3tZbWgaHM0MjM0YRmvW3sSQcBhsrvIAOvYppj2lmGI
    2XsgT9nGd9grTASXePvTuKcIsx4A0GakcH43vulK7VP14LwkFXECqxsbImGhXbH+rv217d
    YJbjmUwEDoZLFZBEqvvf9uB9mUl6HqP2Hg2TYiz3g50K9FFeJxAjYXS0ompeAgGgyAXppV
    DNv4ksumK1O+BBO7pFRdt+ZvWTkmr2XDBaVGF/xjOBG/Vn5fdrwAILF41KzvQa59juz4eK
    W9fxH1DjbsSKZOoWNQoj8o6kDff34uL+p5edJYLuxnz7kR6K+9moRYgjCA+yFeeXyMhftI
    u+6YA7OzShzjwVgpPYZMET/cHC3iuwiPRjAZczCSEbKAt8Zs4qo783BazDM/Jaw9wX90Zq
    hEd476kh4pplSWEUHND4ks4Jsp9pJGrqILybxeeSSo78QXDqamTgs3EW7aLbJ7XG3m1777
    E6Qq+K0vl9HwbaTeHytp53lNSo3DtQAAAAMBAAEAAAGAcB6L68h24M2bMpm4Cn7v9BBp7e
    WloGQbS2zLt7y4QpmSkqzfdR2GpIvmJECgEyOJppJpDOYqvQvD6iA/PLZbMLZgHh1948k6
    7jl2c59gxzl3ws0hHFLilvDQtPVCI/UkvvUl8pr8w4r47kbexBCH+a1e/s2MnO1nw+ueBZ
    AbuZyxdwHp0OISCMn98Gq8sgFkNIy2k0EHoTRPXevtDHoQfWsNefvtHVLsWWQwiMvD/UAp
    6vLZEfGIHqO0YDFFEpTDi1ao0rc2JcUn/uKpQxmnihbsI3i9q1fuuYp3Dus9XQYeJ9ZRuX
    SYHSJxOH2Z0FQzyovqg52bTwpIeFlkfulRI1Q33fASgtJ8GWUrD+Bf6zrZBqU2SWZJ2p0l
    RT88PhOVLwCbn2G1VBVCiBPxn0rPSOizuJn5RcZMcxA8QKkfBylNuIu8A50l0suzTSYZkz
    PeFh5LDkn2CGXp+GGK3fu8AkXv/NIBDttYxZ1p/l8W6+6IMamxrGuI17qbl4c82gt1AAAA
    wQDMGF9xjhc9kDVbofp5FyuuNnaxSaWkDGbZb5hAKng8yArieinsELdUG3rdMtDRWFCicz
    Upyh4LcEkdKH0hSo0g5Clm6dg2wVwLmzp2TazTzF6laqASyUBRM9FJUROZupTgiTMhVK1X
    Bl3TZ3LSrArsGag912rMdtV1KHX+DNvfSb12jHMNm7vNHPfoWzcPe64w8AkqFDWmzhBs04
    JrsUR7vAKiwgltMxewWo2+nLxXqqp03SBymKvvWcRqBDYsnsQAAADBAOpF9MKXVc1pSWSW
    NWJqJMaTYVZKQqjLCpzvMIW1KgQghnT0t5uXoEvP1UO3fd9dtemzEvO47Rt0VEmmXdXPBE
    gvnrlRUiKHn9EKIplaWePRNo4weP2YArFZGeUD8DjaqZCmD2p4WjXUQDkyCyAGwy8ifj4+
    /UmScnZ7obj8H9T9RKQ6dH7biDwPXSbuPrJVcGZaNS6tbZnXEwOam/qaWZeE4XagqJntt9
    X3qCqGUOrKJgmvVBcY+CvVTz+F7XKdMwAAAMEA0UeEm5a/6IDoEnixwnEq2vtb87QT9jQn
    UORJOGtVzCH2nT+f9QC7ghky8jTaAgS4VjNHCg23rlSd6SeywlhhIJb+imxNjh8ODmAeiq
    I9Jcfs63OtLghjV3OqqMZGCH+p7npgnhwfT/n9BEJKnk22aMu5Ns0+MBQEFfL4UOlIOs1d
    gEOzZGoCmSFZ4r7SBnt02K4EUMzmS5y/M/eA02OOQ+789evCBx7+NUp/MYwecqh2EkCA9I
    l8aPYaW0udZIt3AAAAGWZhdXppQGFjY2VsYnl0ZS5uZXRAbGludXgB
    -----END OPENSSH PRIVATE KEY-----
  identity.pub: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/hI+UNAkpucsCWR7w/Kj97WW1oGhzNDIzNGEZr1t7EkHAYbK7yADr2KaY9pZhiNl7IE/ZxnfYK0wEl3j707inCLMeANBmpHB+N77pSu1T9eC8JBVxAqsbGyJhoV2x/q79te3WCW45lMBA6GSxWQRKr73/bgfZlJeh6j9h4Nk2Is94OdCvRRXicQI2F0tKJqXgIBoMgF6aVQzb+JLLpitTvgQTu6RUXbfmb1k5Jq9lwwWlRhf8YzgRv1Z+X3a8ACCxeNSs70GufY7s+HilvX8R9Q427EimTqFjUKI/KOpA339+Li/qeXnSWC7sZ8+5EeivvZqEWIIwgPshXnl8jIX7SLvumAOzs0oc48FYKT2GTBE/3Bwt4rsIj0YwGXMwkhGygLfGbOKqO/NwWswzPyWsPcF/dGaoRHeO+pIeKaZUlhFBzQ+JLOCbKfaSRq6iC8m8XnkkqO/EFw6mpk4LNxFu2i2ye1xt5te++xOkKvitL5fR8G2k3h8raed5TUqNw7U=
  known_hosts: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=

