---
apiVersion: v1
kind: Secret
metadata:
  name: deployment-repo-auth-apple
  namespace: apple
stringData:
  identity: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAArAAAABNlY2RzYS
    1zaGEyLW5pc3RwNTIxAAAACG5pc3RwNTIxAAAAhQQAllQ/xJTLZbiWKjszf7hra5UQ7N2d
    yLGXasR6/g7pjr778Xfg31BjJL5uz4x+lOsp2RbPZSzWH4QZ37kgtADUz8sBNk8ob012oS
    ixwlYXZ9ChnjY85wwamDC86aolMbANda6GVTX13pNboAOFONTLnDhGUXKBALBBm10DR2bv
    0krqzo4AAAEY05ntuNOZ7bgAAAATZWNkc2Etc2hhMi1uaXN0cDUyMQAAAAhuaXN0cDUyMQ
    AAAIUEAJZUP8SUy2W4lio7M3+4a2uVEOzdncixl2rEev4O6Y6++/F34N9QYyS+bs+MfpTr
    KdkWz2Us1h+EGd+5ILQA1M/LATZPKG9NdqEoscJWF2fQoZ42POcMGpgwvOmqJTGwDXWuhl
    U19d6TW6ADhTjUy5w4RlFygQCwQZtdA0dm79JK6s6OAAAAQUyQrvsOKeaoiSOC4IFkFJ9V
    e295XD04Wu7UkU4wfWxOlls5TrT3AqRPLWAjXe39duET/P/Iz47pig+0bTKSgdnvAAAAFW
    lzbGFtaWZhdXppQGdtYWlsLmNvbQECAwQFBg==
    -----END OPENSSH PRIVATE KEY-----
  identity.pub: |
    ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBACWVD/ElMtluJYqOzN/uGtrlRDs3Z3IsZdqxHr+DumOvvvxd+DfUGMkvm7PjH6U6ynZFs9lLNYfhBnfuSC0ANTPywE2TyhvTXahKLHCVhdn0KGeNjznDBqYMLzpqiUxsA11roZVNfXek1ugA4U41MucOEZRcoEAsEGbXQNHZu/SSurOjg==
  known_hosts: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=

